/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/error-boundary`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/game/CategorySelect`; params?: Router.UnknownInputParams; } | { pathname: `/game/CelebrationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/game/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level1Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level2Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level3Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level4Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level5Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/LevelIntroScreen`; params?: Router.UnknownInputParams; } | { pathname: `/game/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/game/TeacherPanelScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/error-boundary`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/game/CategorySelect`; params?: Router.UnknownOutputParams; } | { pathname: `/game/CelebrationScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/Level1Screen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/Level2Screen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/Level3Screen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/Level4Screen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/Level5Screen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/LevelIntroScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/SplashScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/game/TeacherPanelScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/error-boundary${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/game/CategorySelect${`?${string}` | `#${string}` | ''}` | `/game/CelebrationScreen${`?${string}` | `#${string}` | ''}` | `/game/HomeScreen${`?${string}` | `#${string}` | ''}` | `/game/Level1Screen${`?${string}` | `#${string}` | ''}` | `/game/Level2Screen${`?${string}` | `#${string}` | ''}` | `/game/Level3Screen${`?${string}` | `#${string}` | ''}` | `/game/Level4Screen${`?${string}` | `#${string}` | ''}` | `/game/Level5Screen${`?${string}` | `#${string}` | ''}` | `/game/LevelIntroScreen${`?${string}` | `#${string}` | ''}` | `/game/SplashScreen${`?${string}` | `#${string}` | ''}` | `/game/TeacherPanelScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/error-boundary`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/game/CategorySelect`; params?: Router.UnknownInputParams; } | { pathname: `/game/CelebrationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/game/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level1Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level2Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level3Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level4Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/Level5Screen`; params?: Router.UnknownInputParams; } | { pathname: `/game/LevelIntroScreen`; params?: Router.UnknownInputParams; } | { pathname: `/game/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/game/TeacherPanelScreen`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
